# Copyright (c) 2018 Piero Dalle Pezze
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

language: r
sudo: required
cache: packages
r:
  # We don't actually use the Travis R, but this keeps it organized.
  - release
install:

  # install xvfb
  # we don't have X11 on Travis-CI, so we use a virtual framebuffer
  # because R packages for generating figures were compiled with X11
  # support.
  - sudo apt-get update
  - sudo apt-get install xvfb
  - PID=$$
  # create a virtual screen and suppress the output
  - Xvfb :$PID -screen 0 800x600x16 2>/dev/null 1>&2 &
  - xvfb_pid=$!
  - export DISPLAY=:$PID.0


  # install miniconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # install SBpiper's R dependencies from Anaconda Cloud.
  # create the `sbpiper` environment
  - conda env create --name sbpiper --file environment.yaml
  - source activate sbpiper

# command to run tests
script:
  - rm miniconda.sh
  - R CMD build .
  - R CMD check *tar.gz --as-cran
