# This file is part of sbpipe.
#
# sbpipe is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# sbpipe is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with sbpipe.  If not, see <http://www.gnu.org/licenses/>.



package:
  name: sbpiper
  version: 1.0

about:
  summary: R functions for SBpipe
  home: https://github.com/pdp10/sbpiper
  readme: README.md
  license: LGPL-3.0
  license_file: LICENSE

build:
    number: '0'
    rpaths:
        - lib/
        - lib/R/lib/

source:
  #git_tag: v3.13.0
  #git_url: https://github.com/pdp10/sbpipe.git
  path: ../

requirements:
    build:
        - r-base 3.4.2
        - r-ggplot2
        - r-hmisc
        - r-reshape2
        - r-plyr
        - r-scales
    run:
        - r-base 3.4.2
        - r-ggplot2
        - r-hmisc
        - r-reshape2
        - r-plyr
        - r-scales
test:
    commands:
        - $R -e "library('sbpiper')"

