# Copyright (c) 2018 Piero Dalle Pezze
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

{% set version= "1.9.0" %}

package:
  name: "sbpiper"
  version: '{{ version }}'

source:
  git_rev: develop
  git_url: https://github.com/pdp10/sbpiper.git
  
build:
  number: '0'
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base 3.4.*
    - r-data.table
    - r-ggplot2 2.2.*
    - r-reshape2
    - r-hmisc  
    - r-scales
    - r-stringr
    - r-colorramps
    - r-factoextra
    - r-factominer
  run:
    - r-base 3.4.*
    - r-data.table
    - r-ggplot2 2.2.*
    - r-reshape2
    - r-hmisc  
    - r-scales
    - r-stringr
    - r-colorramps
    - r-factoextra
    - r-factominer

test:
  commands:
    - $R -e "library('sbpiper')"

about:
  home: https://cran.r-project.org/package=sbpiper
  license: MIT
  summary: Provides an API for analysing repetitive parameter estimations and simulations of mathematical models. Examples of mathematical models are Ordinary Differential equations (ODEs) or Stochastic Differential Equations (SDEs) models. Among the analyses for parameter estimation sbpiper calculates statistics and generates plots for parameter density, PCA of the best fits, parameter profile likelihood estimations (PLEs), and 2D parameter PLEs. These results can  be generated using all or a subset of the best computed parameter sets. Among the analyses for model simulation sbpiper calculates statistics and generates plots for deterministic and stochastic time courses via cartesian and heatmap plots. Plots for the scan of one or two model parameters can also be generated."

extra:
  recipe-maintainers: 'Piero Dalle Pezze'
  identifiers:
    - doi:10.1186/s12918-017-0423-3
