# This file is part of sbpiper.
#
# sbpiper is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# sbpiper is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with sbpiper.  If not, see <http://www.gnu.org/licenses/>.


{% set version= '1.6.0' %}

package:
  name: sbpiper
  version: {{ version }}

source:
  git_rev: develop
  git_url: https://github.com/pdp10/sbpiper.git
  #path: ../
  
about:
  summary: R functions for SBpipe
  home: https://github.com/pdp10/sbpiper
  license: LGPL-3.0
  license_file: LICENSE

build:
    number: '0'
    rpaths:
        - lib/
        - lib/R/lib/

requirements:
    build:
        - r-base=3.4.2
        - r-data.table
        - r-ggplot2>=2.2.0
        - r-reshape2
        - r-hmisc        
        - r-scales
        - r-stringr
        - r-colorramps
        #- r-essentials       
    run:
        - r-base=3.4.2    
        - r-data.table
        - r-ggplot2>=2.2.0
        - r-reshape2
        - r-hmisc
        - r-scales
        - r-stringr
        - r-colorramps
        #- r-essentials       
test:
    commands:
        - $R -e "library('sbpiper')"
